name: Clang Format

on:
  push:
    branches:
    - 'main'
    - 'development'
  pull_request:
    branches:
    - 'main'
    - 'development'

jobs:
  format:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang Format
        run: |
          sudo apt-get install wget
          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install clang-format-18

      - name: Get Clang Format Version
        run: clang-format-18 --version
        
      - name: Run Clang Format
        run: |
          find . -name '*.cpp' -o -name '*.h' -o -name '*.c' | xargs clang-format -i -style='{SortIncludes: false}'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format code with clang-format"
          branch: ${{ github.head_ref }}
