name: Memory Leak Check

on: [push, pull_request]

jobs:
  memory-leak-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind cmake g++

      - name: Install auto tools
        run: |
          sudo apt-get install automake
      
      - name: Download Linaro tools and untar
        run: |
          wget -c https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
          tar xf gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz
  
      - name: Set Up Build Environment and compile code for LE platform
        run: |
    
          # Set Up Build Environment
          export PATH="$PWD/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu/bin/:$PATH"
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          export AS=aarch64-linux-gnu-as
          export LD=aarch64-linux-gnu-ld
          export RANLIB=aarch64-linux-gnu-ranlib
          export STRIP=aarch64-linux-gnu-strip
          
          # Compile the source code
          chmod 777 gitcompile
          ./gitcompile --host=aarch64-linux-gnu

      - name: Run memory leak check
        run: |
          echo "Verify the compiled binaries"
          Files=("src/adsprpcd
            src/cdsprpcd
            src/sdsprpcd")
          for File in $Files
          do 
           if [ -f $File ] ; then valgrind --leak-check=full ./$File ; else echo $File " - Not Exists" && exit -1 ; fi
          done
